function [num_indexes,indexes] = load_indexes(name_dataset)

if name_dataset == "IP220"
    indexes = [
        load("indexes\IP220\1.mat").indexes...
        load("indexes\IP220\2.mat").indexes...
        load("indexes\IP220\3.mat").indexes...
        load("indexes\IP220\4.mat").indexes...
        load("indexes\IP220\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "IP200"
    indexes = [
        load("indexes\IP220\1.mat").indexes...
        load("indexes\IP220\2.mat").indexes...
        load("indexes\IP220\3.mat").indexes...
        load("indexes\IP220\4.mat").indexes...
        load("indexes\IP220\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "PU103"
    indexes = [
        load("indexes\PU103\1.mat").indexes...
        load("indexes\PU103\2.mat").indexes...
        load("indexes\PU103\3.mat").indexes...
        load("indexes\PU103\4.mat").indexes...
        load("indexes\PU103\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "HO144"
    indexes = [
        load("indexes\HO144\1.mat").indexes...
        load("indexes\HO144\2.mat").indexes...
        load("indexes\HO144\3.mat").indexes...
        load("indexes\HO144\4.mat").indexes...
        load("indexes\HO144\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end


if name_dataset == "SA224"
    indexes = [
        load("indexes\SA224\1.mat").indexes...
        load("indexes\SA224\2.mat").indexes...
        load("indexes\SA224\3.mat").indexes...
        load("indexes\SA224\4.mat").indexes...
        load("indexes\SA224\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "SA204"
    indexes = [
        load("indexes\SA224\1.mat").indexes...
        load("indexes\SA224\2.mat").indexes...
        load("indexes\SA224\3.mat").indexes...
        load("indexes\SA224\4.mat").indexes...
        load("indexes\SA224\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "DC191"
    indexes = [
        load("indexes\DC191\1.mat").indexes...
        load("indexes\DC191\2.mat").indexes...
        load("indexes\DC191\3.mat").indexes...
        load("indexes\DC191\4.mat").indexes...
        load("indexes\DC191\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "KS176"
    indexes = [
        load("indexes\KS176\1.mat").indexes...
        load("indexes\KS176\2.mat").indexes...
        load("indexes\KS176\3.mat").indexes...
        load("indexes\KS176\4.mat").indexes...
        load("indexes\KS176\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end

if name_dataset == "G5150"
    indexes = [
        load("indexes\G5150\1.mat").indexes...
        load("indexes\G5150\2.mat").indexes...
        load("indexes\G5150\3.mat").indexes...
        load("indexes\G5150\4.mat").indexes...
        load("indexes\G5150\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end
if name_dataset == "HH270"
    indexes = [
        load("indexes\HH270\1.mat").indexes...
        load("indexes\HH270\2.mat").indexes...
        load("indexes\HH270\3.mat").indexes...
        load("indexes\HH270\4.mat").indexes...
        load("indexes\HH270\5.mat").indexes...
    ];
    [num_indexes,~] = size(indexes);
end
